CREATE OR REPLACE DATABASE SNOWPARK_DB;

USE DATABASE SNOWPARK_DB;

CREATE OR REPLACE SCHEMA STAGING;
CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA TRANSFORMED;
CREATE OR REPLACE SCHEMA CURATED;

USE SCHEMA SNOWPARK_DB.STAGING;

CREATE OR REPLACE TABLE SNOWPARK_DB.STAGING.INDIA_SALES_ORDER_CP
(
ORDER_ID VARCHAR(1000),
CUSTOMER_NAME VARCHAR(1000),
MOBILE_MODEL VARCHAR(1000),
QUANTITY VARCHAR(1000),
PRICE_PER_UNIT VARCHAR(1000),
TOTAL_PRICE VARCHAR(1000),
PROMOTION_CODE VARCHAR(1000),
ORDER_AMOUNT VARCHAR(1000),
GST VARCHAR(1000),
ORDER_DATE VARCHAR(1000),
PAYMENT_STATUS VARCHAR(1000),
SHIPPING_STATUS VARCHAR(1000),
PAYMENT_METHOD VARCHAR(1000),
PAYMENT_PROVIDER VARCHAR(1000),
MOBILE VARCHAR(1000),
DELIVERY_ADDRESS VARCHAR(1000)
);
--PARQUET
CREATE OR REPLACE TABLE SNOWPARK_DB.STAGING.USA_SALES_ORDER_CP
(
SOURCE_DATA VARIANT
);
--JSON
CREATE OR REPLACE TABLE SNOWPARK_DB.STAGING.FRANCE_SALES_ORDER_CP
(
SOURCE_DATA VARIANT
);

//CREATE STORAGE INTEGRATION 

CREATE OR REPLACE STORAGE INTEGRATION SNOWPARK_S3_INT
    TYPE=EXTERNAL_STAGE
    STORAGE_PROVIDER='S3'
    ENABLED=TRUE
    STORAGE_AWS_ROLE_ARN='arn:aws:iam::915079918968:role/snowflakerole' //IAM ROLE --> ARN
    STORAGE_ALLOWED_LOCATIONS=('s3://aj-snowpark-data-bucket/'); // FROM S3 BUCKET S3 URI OF FOLDER

// IAM ROLE AND EXTERNAL ID FROM SNOWFLAKE AND UPDATE AWS

DESC INTEGRATION SNOWPARK_S3_INT;

//CREATE EXTERNAL STAGE --> ACCESS FILE FROM S3 BUCKET

CREATE STAGE SNOWPARK_DB.STAGING.SNOWPARK_STAGE
STORAGE_INTEGRATION=SNOWPARK_S3_INT
URL= 's3://aj-snowpark-data-bucket/';

//VALIDATE SETUP -- TRUST AS EXPECTED

LS @SNOWPARK_DB.STAGING.SNOWPARK_STAGE;


SELECT * FROM SNOWPARK_DB.TRANSFORMED.GLOBAL_SALES_ORDER;

select * from snowpark_db.curated.global_sales_order_brand;
select * from snowpark_db.curated.global_sales_order_country;
select * from snowpark_db.curated.global_sales_order_delivered;